In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
tf.__version__

'2.12.0'

In [ ]:
dataset = pd.read_csv('cpu.csv')
dataset.head(20)

vendor  MYCT   MMIN   MMAX  CACH  CHMIN  CHMAX  class
0     adviser   125    256   6000   256     16    128    199
1      amdahl    29   8000  32000    32      8     32    253
2      amdahl    29   8000  32000    32      8     32    253
3      amdahl    29   8000  32000    32      8     32    253
4      amdahl    29   8000  16000    32      8     16    132
5      amdahl    26   8000  32000    64      8     32    290
6      amdahl    23  16000  32000    64     16     32    381
7      amdahl    23  16000  32000    64     16     32    381
8      amdahl    23  16000  64000    64     16     32    749
9      amdahl    23  32000  64000   128     32     64   1238
10     apollo   400   1000   3000     0      1      2     23
11     apollo   400    512   3500     4      1      6     24
12       basf    60   2000   8000    65      1      8     70
13       basf    50   4000  16000    65      1      8    117
14        bti   350     64     64     0      1      4     15
15        bti   200    512  16000     0      4     32     64
16  burroughs   167    524   2000     8      4     15     23
17  burroughs   143    512   5000     0      7     32     29
18  burroughs   143   1000   2000     0      5     16     22
19  burroughs   110   5000   5000   142      8     64    124

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   vendor  209 non-null    object
 1   MYCT    209 non-null    int64 
 2   MMIN    209 non-null    int64 
 3   MMAX    209 non-null    int64 
 4   CACH    209 non-null    int64 
 5   CHMIN   209 non-null    int64 
 6   CHMAX   209 non-null    int64 
 7   class   209 non-null    int64 
dtypes: int64(7), object(1)
memory usage: 13.2+ KB


In [ ]:
X = dataset.drop(["vendor", "class"], axis = 1)
y = dataset["class"]

In [ ]:
X.head()

MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX
0   125   256   6000   256     16    128
1    29  8000  32000    32      8     32
2    29  8000  32000    32      8     32
3    29  8000  32000    32      8     32
4    29  8000  16000    32      8     16

In [ ]:
y.head()

0    199
1    253
2    253
3    253
4    132
Name: class, dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = MinMaxScaler()
#scaler = StandardScaler
X = scaler.fit_transform(X)

In [ ]:
X

array([[0.07282535, 0.00601202, 0.09284284, 1.        , 0.30769231,
        0.72727273],
       [0.00809171, 0.24849699, 0.4994995 , 0.125     , 0.15384615,
        0.18181818],
       [0.00809171, 0.24849699, 0.4994995 , 0.125     , 0.15384615,
        0.18181818],
       ...,
       [0.07282535, 0.06062124, 0.12412412, 0.        , 0.03846154,
        0.07954545],
       [0.31220499, 0.01402806, 0.12412412, 0.125     , 0.        ,
        0.        ],
       [0.31220499, 0.02930862, 0.06156156, 0.        , 0.        ,
        0.        ]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='linear'))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_logarithmic_error', metrics = ['accuracy'])

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=50)

In [ ]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Cargar el conjunto de datos
data = pd.read_csv('cpu.csv')

# Obtener las características de entrada y las etiquetas de salida
X = data.iloc[:, 1:-1].values  # Todas las columnas excepto la primera y la última
y = data.iloc[:, -1].values   # Última columna (etiquetas)

# Normalizar las características
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Dividir el dataset en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Definir el modelo
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(X_train.shape[1],))
])

# Compilar el modelo
model.compile(optimizer='sgd', loss='mse')

# Entrenar el modelo
num_epochs = 1000
model.fit(X_train, y_train, epochs=num_epochs, verbose=1)

# Realizar predicciones en el conjunto de prueba


Epoch 1/1000
6/6 [==============================] - 1s 4ms/step - loss: 21394.9043
Epoch 2/1000
6/6 [==============================] - 0s 3ms/step - loss: 14929.7725
Epoch 3/1000
6/6 [==============================] - 0s 3ms/step - loss: 9261.1914
Epoch 4/1000
6/6 [==============================] - 0s 4ms/step - loss: 7531.4385
Epoch 5/1000
6/6 [==============================] - 0s 3ms/step - loss: 6298.3887
Epoch 6/1000
6/6 [==============================] - 0s 3ms/step - loss: 5299.3701
Epoch 7/1000
6/6 [==============================] - 0s 3ms/step - loss: 4595.9111
Epoch 8/1000
6/6 [==============================] - 0s 4ms/step - loss: 3962.6887
Epoch 9/1000
6/6 [==============================] - 0s 4ms/step - loss: 3508.1792
Epoch 10/1000
6/6 [==============================] - 0s 3ms/step - loss: 3118.9292
Epoch 11/1000
6/6 [==============================] - 0s 3ms/step - loss: 2859.5725
Epoch 12/1000
6/6 [==============================] - 0s 2ms/step - loss: 2575.8916
Epoch 13/10

In [ ]:
y_pred_test = model.predict(X_test)
print("Predicciones:", y_pred_test)

from sklearn.metrics import confusion_matrix

# Suponiendo que 'y_true' es la lista de etiquetas reales y 'y_pred' es la lista de etiquetas predichas
cm = confusion_matrix(y_test, y_pred_test)
print("Matriz de confusión:")
print(cm)

2/2 [==============================] - 0s 6ms/step
Predicciones: [[ 7.9719528e+01]
 [-1.6476212e+00]
 [ 6.6169815e+00]
 [ 6.6587860e+02]
 [ 4.9227798e+01]
 [ 2.9982315e+02]
 [ 3.4681458e+01]
 [-2.0487183e+01]
 [ 8.0337677e+02]
 [ 2.6205997e+02]
 [ 1.0677295e+02]
 [ 1.2592235e+02]
 [ 3.9260918e+01]
 [ 3.3701683e+01]
 [ 9.9915512e+01]
 [ 1.1441978e+01]
 [ 8.7666351e+01]
 [-7.9742432e+00]
 [ 1.7656674e+02]
 [ 1.0741652e+02]
 [ 7.6776398e+01]
 [ 5.6729778e+01]
 [ 1.4363354e+02]
 [ 3.4123718e+01]
 [ 6.8292694e+00]
 [ 3.3288353e+01]
 [-1.2061783e+01]
 [ 1.4229660e+00]
 [-6.9875412e+00]
 [ 7.4315811e+01]
 [ 2.9267902e+02]
 [ 1.9941322e+01]
 [ 1.4909088e+01]
 [-2.1548943e+01]
 [ 9.3055725e-02]
 [ 3.7071587e+01]
 [ 5.1525715e+01]
 [ 3.7006287e+02]
 [ 1.8110573e+02]
 [-7.1736374e+00]
 [ 3.4566055e+02]
 [ 4.8360725e+01]]


ValueError: ignored

In [ ]:
y_pred_test


array([[ 7.9719528e+01],
       [-1.6476212e+00],
       [ 6.6169815e+00],
       [ 6.6587860e+02],
       [ 4.9227798e+01],
       [ 2.9982315e+02],
       [ 3.4681458e+01],
       [-2.0487183e+01],
       [ 8.0337677e+02],
       [ 2.6205997e+02],
       [ 1.0677295e+02],
       [ 1.2592235e+02],
       [ 3.9260918e+01],
       [ 3.3701683e+01],
       [ 9.9915512e+01],
       [ 1.1441978e+01],
       [ 8.7666351e+01],
       [-7.9742432e+00],
       [ 1.7656674e+02],
       [ 1.0741652e+02],
       [ 7.6776398e+01],
       [ 5.6729778e+01],
       [ 1.4363354e+02],
       [ 3.4123718e+01],
       [ 6.8292694e+00],
       [ 3.3288353e+01],
       [-1.2061783e+01],
       [ 1.4229660e+00],
       [-6.9875412e+00],
       [ 7.4315811e+01],
       [ 2.9267902e+02],
       [ 1.9941322e+01],
       [ 1.4909088e+01],
       [-2.1548943e+01],
       [ 9.3055725e-02],
       [ 3.7071587e+01],
       [ 5.1525715e+01],
       [ 3.7006287e+02],
       [ 1.8110573e+02],
       [-7.1736374e+00],


In [ ]:
y_test

array([ 102,   25,   25,  919,   34,  267,   41,   19, 1238,  227,   88,
         99,   41,   44,   64,   23,   80,   22,  142,   82,   52,   56,
        119,   26,   17,   41,   21,   30,   23,   67,  275,   33,   35,
         20,   20,   46,   47,  361,   73,   26,  341,   47])